name: test
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pytest
        run: pip install pytest
      
      - name: Install numpy
        run: pip install numpy
      
      - name: Run pytest
        run: pytest test_sequence.py